[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
    adafruit/Adafruit ICM20X@^2.0.0
    adafruit/Adafruit BusIO@^1.14.0
build_flags =
    -DESP32
    -I include
    -Os
board_build.partitions = huge_app.csv