[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3
lib_deps =
    tanakamasayuki/TensorFlowLite_ESP32@^1.0.0
    adafruit/Adafruit ICM20948@^1.0.3
    adafruit/Adafruit BusIO@^1.14.0
build_flags =
    -DESP32
    -I include
    -Os